"""Monthly report: summary, top 3 actions, KPIs and a downloadable PDF."""
from io import BytesIO

import pandas as pd
from reportlab.graphics.charts.barcharts import HorizontalBarChart
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from . import analytics as an
from . import db
from .config import POSITIVE_ISSUE, REPORT_DIR
from .playbook import recommend
from .replies import monthly_summary

ACCENT = colors.HexColor("#0F6E56")


def build_report(df, restaurant, month: str) -> dict:
    """month = 'YYYY-MM'."""
    p = pd.Period(month, "M")
    start, end = p.start_time, p.end_time.normalize()
    prev = p - 1
    rest = an.filter_reviews(df, restaurant)
    cur = an.filter_reviews(rest, start=start, end=end)
    prv = an.filter_reviews(rest, start=prev.start_time, end=prev.end_time.normalize())

    k = an.kpis(cur, prv, end)
    issues = an.top_issues(cur, prv)
    prio = an.priority_table(cur)
    sp = an.spikes(rest, min(end, rest["review_date"].max()) if len(rest) else end)
    rs = an.reply_stats(cur)
    by_src = cur["source"].value_counts().to_dict()

    rising = issues.dropna(subset=["change_pct"]).sort_values("change_pct")
    facts = {
        "reviews": k["reviews"], "sources": by_src, "score": k["score"], "score_delta": k["score_delta"],
        "negative_share_pct": round(k["neg_share"], 1),
        "top_issue": issues["issue"].iat[0] if len(issues) else None,
        "top_issue_count": int(issues["mentions"].iat[0]) if len(issues) else 0,
        "biggest_rise": (f"{rising['issue'].iat[-1]} ({rising['change_pct'].iat[-1]:+.0f}%)"
                         if len(rising) and rising["change_pct"].iat[-1] > 0 else None),
        "biggest_fall": (rising["issue"].iat[0] if len(rising) and rising["change_pct"].iat[0] < 0 else None),
        "spike": (f"{sp['issue'].iat[0]} at {sp['branch'].iat[0]} ({sp['ratio'].iat[0]:.1f}x its weekly average)"
                  if len(sp) else None),
    }
    summary, engine = monthly_summary(restaurant, p.strftime("%B %Y"), facts)

    actions = []
    for _, row in prio.head(3).iterrows():
        d = cur[(cur["issue"] == row["issue"]) & (cur["sentiment"] != "positive")]
        branch = d["branch"].mode().iat[0] if len(d) else "all branches"
        rec = recommend(row["issue"], branch)
        actions.append({"issue": row["issue"], "action": rec["action"], "owner": rec["owner"],
                        "expected": rec["expected"], "priority": str(row["priority"])})

    return {"restaurant": restaurant, "month": month, "label": p.strftime("%B %Y"), "kpis": k, "facts": facts,
            "summary": summary, "engine": engine, "actions": actions, "issues": issues, "priority": prio,
            "branches": an.branch_table(cur), "reply": rs, "sources": by_src}


def _fmt(v, suffix="", nd=0):
    return "-" if v is None or pd.isna(v) else f"{v:.{nd}f}{suffix}"


def build_pdf(r: dict) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=16 * mm, bottomMargin=16 * mm,
                            title=f"{r['restaurant']} {r['label']} review report")
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], alignment=0, fontSize=18, textColor=ACCENT, spaceAfter=2)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], fontSize=12, textColor=ACCENT, spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("b", parent=ss["BodyText"], fontSize=9.5, leading=13)
    small = ParagraphStyle("s", parent=body, fontSize=8, textColor=colors.grey)
    k, rp = r["kpis"], r["reply"]
    src = " · ".join(f"{s} {n}" for s, n in r["sources"].items())
    grid = TableStyle([("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey),
                       ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E1F5EE")),
                       ("FONTSIZE", (0, 0), (-1, -1), 8.5), ("VALIGN", (0, 0), (-1, -1), "TOP")])

    el = [Paragraph(f"{r['restaurant']} · {r['label']} report", h1),
          Paragraph(f"{k['reviews']} reviews ({src}) · generated by Empathy Engine", small),
          Paragraph("Summary", h2), Paragraph(r["summary"], body), Paragraph("Key numbers", h2)]
    kt = [["Reputation score", "Change", "Avg rating", "Negative share", "Reply rate", "Median reply time", "Escalations resolved"],
          [_fmt(k["score"], "/100", 1), _fmt(k["score_delta"], " pts", 1), _fmt(k["avg_rating"], "", 2),
           _fmt(k["neg_share"], "%", 1), _fmt(rp["reply_rate"], "%"), _fmt(rp["avg_reply_hours"], " h"),
           f"{rp['resolved']}/{rp['escalations']}"]]
    el.append(Table(kt, style=grid))

    el.append(Paragraph("Top 3 actions for next month", h2))
    at = [["#", "Issue", "Action", "Owner", "Expected result"]] + [
        [i + 1, Paragraph(a["issue"], body), Paragraph(a["action"], body), a["owner"], Paragraph(a["expected"], body)]
        for i, a in enumerate(r["actions"])]
    el.append(Table(at, colWidths=[8 * mm, 38 * mm, 62 * mm, 26 * mm, 40 * mm], style=grid))

    iss = r["issues"].head(8)
    if len(iss):
        el.append(Paragraph("Complaint themes", h2))
        d = Drawing(170 * mm, 8 * mm * len(iss) + 10)
        ch = HorizontalBarChart()
        ch.x, ch.y, ch.width, ch.height = 62 * mm, 5, 100 * mm, 8 * mm * len(iss)
        ch.data = [list(iss["mentions"][::-1])]
        ch.categoryAxis.categoryNames = [s[:38] for s in iss["issue"][::-1]]
        ch.categoryAxis.labels.fontSize = 7.5
        ch.categoryAxis.labels.fontName = ch.valueAxis.labels.fontName = "Helvetica"
        ch.valueAxis.labels.fontSize = 7
        ch.valueAxis.valueMin = 0
        ch.bars[0].fillColor = ACCENT
        ch.bars[0].strokeColor = None
        d.add(ch)
        el.append(d)
        it = [["Issue", "Mentions", "Last month", "Change"]] + [
            [row.issue, int(row.mentions), int(row.previous), _fmt(row.change_pct, "%")] for row in iss.itertuples()]
        el.append(Spacer(1, 4))
        el.append(Table(it, colWidths=[80 * mm, 25 * mm, 25 * mm, 25 * mm], style=grid))

    b = r["branches"]
    if len(b):
        el.append(Paragraph("Branches (lowest score first)", h2))
        bt = [["Branch", "Reviews", "Avg rating", "Negative %", "Score", "Top complaint"]] + [
            [row.branch, row.reviews, _fmt(row.avg_rating, "", 2), _fmt(row.negative_pct, "%", 1), _fmt(row.score, "", 1),
             Paragraph(str(row.top_complaint), body)] for row in b.head(15).itertuples()]
        el.append(Table(bt, colWidths=[35 * mm, 18 * mm, 20 * mm, 20 * mm, 15 * mm, 66 * mm], style=grid))
    el.append(Spacer(1, 8))
    el.append(Paragraph("Reputation score = 60% average rating (rescaled 1-5 to 0-100) + 40% net sentiment. "
                        "Priority = 0.4 × frequency + 0.3 × negative share + 0.3 × low rating.", small))
    doc.build(el)
    return buf.getvalue()


def save_report(r: dict) -> tuple[bytes, str]:
    pdf = build_pdf(r)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORT_DIR / f"{r['restaurant'].replace(' ', '_')}_{r['month']}.pdf"
    path.write_bytes(pdf)
    db.save_report(r["restaurant"], r["month"], r["summary"], path)
    return pdf, str(path)
